---
title: "Kaggle: Model version 1"
always_allow_html: true
editor_options: 
  chunk_output_type: inline
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80), tidy=FALSE) 
```

```{r package, message=FALSE, warning=FALSE}
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(zoo)
library(kableExtra)
library(readxl)
library(xts)
```

```{r}
#Importing time series data (relative humidity and temperature optional but importing)

#load data: this is daily data, with 24 different sensors
load_data <- read_excel(
  path = "./Data/load.xlsx",
  sheet = 1
)

#relative humidity: hourly data, with 28 different sensors
relative_humidity_data <- read_excel(
  path = "./Data/relative_humidity.xlsx",
  sheet = 1
)

#temperature data: hourly data, with 28 different sensors
temperature_data <- read_excel(
  path = "./Data/temperature.xlsx",
  sheet = 1
)

#Preparing load data - create date object
load_processed <- load_data %>%
  mutate(date = ymd(date))

summary(load_processed)

#There are 6 NAs in h2

#Turn load into time series data
n_h <- ncol(load_processed)-2
ts_load_daily <- msts(load_processed[,3:(2+n_h)], seasonal.periods = c(7,365.25), start = c(2005, 1,1))

#cleaning out the NAs for h2
ts_load_daily[, 2] <- tsclean(ts_load_daily[, 2])
```

#Creating training and testing subsets
```{r message=FALSE, warning=FALSE}
n_for <- 365

# Get number of time steps
n_obs <- nrow(ts_load_daily)

#Get cutoff point for train/test
cut_point <- n_obs - n_for

# TRAIN SET (chatGPT said to use window instead to make the proper multivariate time series slices!)
ts_load_train <- window(ts_load_daily, end = time(ts_load_daily)[cut_point])

# TEST SET
ts_load_test <- window(ts_load_daily, start = time(ts_load_daily)[cut_point + 1])
```

#Plotting Data
```{r message=FALSE, warning=FALSE}
for (i in 1:n_h) {
  train_ts <- ts_load_train[, i]
  test_ts  <- ts_load_test[, i]
  
  print(
    autoplot(train_ts, series = "Train") +
      autolayer(test_ts, series = "Test") +
      ggtitle(paste("Train vs Test for", colnames(ts_load_daily)[i])) +
      ylab("Load") +
      xlab("Time")
  )
}
```

```{r}
for (i in 1:n_h) {
  sensor_ts <- ts_load_daily[, i]
  sensor_decomp <- mstl(sensor_ts)
  
  print(
    autoplot(sensor_decomp) +
      ggtitle(paste("MSTL Decomposition -", colnames(ts_load_daily)[i])) +
      theme_minimal()
  )
}
```

